# Generated by Django 4.1.1 on 2022-09-27 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='details',
            new_name='description',
        ),
    ]
